# plain slick bad-wolf gruvbox-light gruvbox-dark modern
# solarized-light solarized-dark
[theme]
name = "native"

[icons]
name = "awesome"
[icons.overrides]
volume_empty = " ğŸ”ˆ "
volume_half = " ğŸ”‰ "
volume_full = " ğŸ”Š "
volume_muted = " ğŸ”‡ "
time = " "

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
signal_strength = false
speed_up = false
speed_down = true

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GiB"

[[block]]
block = "memory"
display_type = "memory"
format_mem = " {Mup}%"
format_swap = " {SUp}%"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
block = "battery"
interval = 10
full_format = " full "
format = " {percentage}% {time}% "

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 60
format = "ğŸ“† %a %m/%d %R"
# format = "ğŸ“† %a %m/%d %R | â¤ï¸ ğŸ‡¹ğŸ‡¼"
